const K='oltreuomo-state-v1';
const DEFAULT_RULES={studyXpPerMin:1,gymBase:85,mentalBase:250,trophyBase:250,difficultyStep:.25,rating1:.75,rating2:1,rating3:1.25,skipStart:4,skipBase:50,skipGrowth:1.2,levelBands:[250,300,350,400,450,500,550,600]};
function thresholds(l){const b=s?.rules?.levelBands||DEFAULT_RULES.levelBands;return l<=5?b[0]:l<=10?b[1]:l<=15?b[2]:l<=20?b[3]:l<=25?b[4]:l<=30?b[5]:l<=35?b[6]:b[7]}
function R(){return s.rules||DEFAULT_RULES}
function ratingMult(n){return n===1?R().rating1:n===2?R().rating2:R().rating3}
function difficultyMult(d){return 1+R().difficultyStep*(d||0)}
function skipPenalty(streak){return streak>=R().skipStart?Math.trunc(R().skipBase*Math.pow(R().skipGrowth,streak-R().skipStart)):0}
const defaultState=()=>({day:1,weekday:'Lunedì',categories:{studio:{xp:0},palestra:{xp:0},mentale:{xp:0}},study:{seconds:0,running:false,startedAt:null,exempt:false,skipStreak:0},gym:{status:'pending',rating:null,xp:0,skipStreak:0},history:[],stats:{studySeconds:0,studyDays:0,studyTasks:0,gymWorkouts:0,mentalChallenges:0,mentalByDifficulty:{}},events:[]});
let s=JSON.parse(localStorage.getItem(K)||'null')||defaultState();
if(!s.rules)s.rules=JSON.parse(JSON.stringify(DEFAULT_RULES));
else s.rules={...DEFAULT_RULES,...s.rules,levelBands:Array.isArray(s.rules.levelBands)&&s.rules.levelBands.length===8?s.rules.levelBands:DEFAULT_RULES.levelBands.slice()};
if(s.study && s.study.skipStreak==null)s.study.skipStreak=0;
if(!s.mental)s.mental={name:'Resta 60 min in un ristorante',difficulty:1,remaining:3,status:'active',rating:null,xp:0,skipStreak:0};
if(!s.stats)s.stats={studySeconds:0,studyDays:0,studyTasks:0,gymWorkouts:0,mentalChallenges:0,mentalByDifficulty:{}};
if(!s.stats.mentalByDifficulty)s.stats.mentalByDifficulty={};
if(!s.events)s.events=[];
if(!s.tasks)s.tasks=[
{id:'study-main',name:'Studiare',category:'studio',type:'time',availability:'recurring',weekdays:['Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato','Domenica'],active:true,system:'study'},
{id:'gym-main',name:'Allenamento',category:'palestra',type:'completion',availability:'recurring',weekdays:['Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato','Domenica'],active:true,system:'gym'},
{id:'mental-main',name:s.mental?.name||'Resta 60 min in un ristorante',category:'mentale',type:'completion',availability:'deadline',duration:3,difficulty:s.mental?.difficulty??1,active:true,system:'mental'}
];
// 1.5.1: una Task a scadenza gia completata resta come configurazione storica/futura,
// ma viene marcata chiaramente come COMPLETATA in Gestione.
const mentalConfigured=s.tasks&&s.tasks.find(t=>t.system==='mental');
if(mentalConfigured && s.mental && s.mental.status==='done'){
  mentalConfigured.completed=true;
  mentalConfigured.completedDay=mentalConfigured.completedDay||s.day;
}
if(!s.trophies)s.trophies=[
{id:'study-exam',name:'Supera un esame',category:'studio',categoryLabel:'Studio',difficulty:0,obtained:false,obtainedDay:null,xpAssigned:0},
{id:'gym-bench-120',name:'Panca 120 kg',category:'palestra',categoryLabel:'Palestra',difficulty:1,obtained:false,obtainedDay:null,xpAssigned:0},
{id:'mental-20km',name:'Arriva a 20 km da casa',category:'mentale',categoryLabel:'Salute mentale',difficulty:2,obtained:false,obtainedDay:null,xpAssigned:0}
];
if(s.study.running){s.study.seconds+=Math.max(0,Math.floor((Date.now()-s.study.startedAt)/1000));s.study.startedAt=Date.now()}
const save=()=>localStorage.setItem(K,JSON.stringify(s));
function level(total){let lv=1,x=total;while(x>=thresholds(lv)){x-=thresholds(lv);lv++}return {lv,x,next:thresholds(lv)}}
const overall=()=>Math.floor((level(s.categories.studio.xp).lv+level(s.categories.palestra.xp).lv+level(s.categories.mentale.xp).lv)/3);
function fmt(sec){sec=Math.max(0,Math.floor(sec));return `${String(Math.floor(sec/3600)).padStart(2,'0')}:${String(Math.floor(sec%3600/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function fmtLong(sec){sec=Math.floor(sec||0);const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60);return h?`${h} h ${m} min`:`${m} min`}
function currentSeconds(){return s.study.seconds+(s.study.running?Math.floor((Date.now()-s.study.startedAt)/1000):0)}
let levelFxQueue=[],levelFxBusy=false,trophyFxBusy=false;
function queueLevelFx(type,label,to){levelFxQueue.push({type,label,to});setTimeout(playNextLevelFx,40)}
function playNextLevelFx(){if(levelFxBusy||trophyFxBusy||!levelFxQueue.length)return;levelFxBusy=true;const e=levelFxQueue.shift(),el=document.createElement('div');el.className=`level-fx ${e.type==='up'?'level-up':'level-down'}`;el.innerHTML=`<div class="level-fx-card"><div class="level-fx-kicker">${e.type==='up'?'LEVEL UP':'LEVEL DOWN'}</div><div class="level-fx-category">${e.label}</div><div class="level-fx-level">LV. ${e.to}</div></div>`;document.body.appendChild(el);requestAnimationFrame(()=>el.classList.add('show'));setTimeout(()=>el.classList.add('leave'),1450);setTimeout(()=>{el.remove();levelFxBusy=false;playNextLevelFx()},1900)}
function addXp(cat,amount,label){const before=level(s.categories[cat].xp).lv;s.categories[cat].xp=Math.max(0,s.categories[cat].xp+amount);const after=level(s.categories[cat].xp).lv;if(after!==before){const type=after>before?'up':'down';s.events.push({day:s.day,type,category:label,from:before,to:after});queueLevelFx(type,label,after)}}
function nav(active){return `<nav class="nav"><span class="${active==='home'?'active':''}" onclick="renderHome()">⌂<br>Home</span><span class="${active==='progress'?'active':''}" onclick="renderProgress()">▥<br>Progressi</span><span class="${active==='trophies'?'active':''}" onclick="renderTrophies()">♢<br>Trofei</span><span class="${active==='manage'?'active':''}" onclick="renderManage()">⚙<br>Gestione</span></nav>`}
function customVisibleTasks(){return (s.tasks||[]).filter(t=>!t.system&&t.active&&((!t.completed)||(t.completedDay===s.day))&&(t.availability==='free'||t.availability==='deadline'||(t.availability==='recurring'&&(t.weekdays||[]).includes(s.weekday))))}
function ensureDeadlineState(t){if(t.availability==='deadline'&&!t.completed&&t.deadlineRemaining==null)t.deadlineRemaining=Math.max(1,t.duration||1);return t.deadlineRemaining}
(s.tasks||[]).forEach(ensureDeadlineState);
if(!s.customDay)s.customDay={day:s.day,instances:{}};
function reconcileOpenDay(){if(!s.customDay||s.customDay.day!==s.day)s.customDay={day:s.day,instances:{}};const visible=new Set(customVisibleTasks().map(t=>t.id));Object.keys(s.customDay.instances).forEach(id=>{if(!visible.has(id))delete s.customDay.instances[id]});customVisibleTasks().forEach(t=>{if(!s.customDay.instances[t.id])s.customDay.instances[t.id]={seconds:0,running:false,startedAt:null,status:'pending',rating:null,xp:0}});save()}
function customSeconds(id){const i=s.customDay?.instances?.[id];if(!i)return 0;return i.seconds+(i.running?Math.floor((Date.now()-i.startedAt)/1000):0)}
function customCards(){reconcileOpenDay();return customVisibleTasks().map(t=>{const i=s.customDay.instances[t.id],lv=level(s.categories[t.category].xp).lv,label=catLabel(t.category);if(i.status==='done')return `<section class="card done"><div class="eyebrow">${label.toUpperCase()} · LV.${lv}</div><div class="title">✓ ${t.name.toUpperCase()}</div><div><span class="xp">+${i.xp} XP</span> · <span class="sub">Valutazione ${i.rating}</span></div><div class="row" style="margin-top:14px"><button class="btn ghost" onclick="undoCustomComplete('${t.id}')">ANNULLA</button></div></section>`;if(i.status==='exempt')return `<section class="card"><div class="eyebrow">${label.toUpperCase()} · LV.${lv}</div><div class="title">${t.name}</div><div class="sub">ESONERATO</div><div class="row" style="margin-top:14px"><button class="btn ghost" onclick="undoCustomExempt('${t.id}')">ANNULLA</button></div></section>`;if(t.type==='time')return `<section class="card"><div class="eyebrow">${label.toUpperCase()} · LV.${lv}</div><div class="title">${t.name}</div><div id="ct-${t.id}" class="timer">${fmt(customSeconds(t.id))}</div><div class="row"><button class="btn ${i.running?'red':'green'}" onclick="toggleCustomTimer('${t.id}')">${i.running?'TERMINA':'AVVIA'}</button><button class="btn ghost" onclick="exemptCustom('${t.id}')">ESONERO</button></div></section>`;return `<section class="card"><div class="eyebrow">${label.toUpperCase()} · LV.${lv}</div><div class="title">${t.name}</div><div class="meta">${taskRewardLabel(t)}${t.availability==='deadline'?` · ${ensureDeadlineState(t)} ${ensureDeadlineState(t)===1?'giorno rimanente':'giorni rimanenti'}`:''}</div><div class="row" style="margin-top:14px"><button class="btn green" onclick="completeCustom('${t.id}')">COMPLETA</button><button class="btn ghost" onclick="exemptCustom('${t.id}')">ESONERO</button></div></section>`}).join('')}
window.toggleCustomTimer=id=>{reconcileOpenDay();const i=s.customDay.instances[id];if(!i)return;if(i.running){i.seconds=customSeconds(id);i.running=false;i.startedAt=null}else{i.running=true;i.startedAt=Date.now()}save();renderHome()};
window.exemptCustom=id=>{reconcileOpenDay();const i=s.customDay.instances[id];if(!i)return;i.undoExempt={seconds:i.seconds,running:i.running,startedAt:i.startedAt};if(i.running){i.seconds=customSeconds(id);i.running=false;i.startedAt=null}i.status='exempt';save();renderHome()};
window.undoCustomExempt=id=>{reconcileOpenDay();const i=s.customDay.instances[id];if(!i)return;const u=i.undoExempt;i.status='pending';if(u){i.seconds=u.running?customSeconds(id):u.seconds;i.running=false;i.startedAt=null;delete i.undoExempt}save();renderHome()};
window.completeCustom=id=>{reconcileOpenDay();const t=s.tasks.find(x=>x.id===id),i=s.customDay.instances[id];if(!t||!i)return;let base=t.category==='palestra'?R().gymBase:t.category==='mentale'?R().mentalBase*difficultyMult(t.difficulty||0):0;if(t.type==='time')return;rateDialog(t.name,base,(xp,r)=>{i.undoComplete={xpBefore:s.categories[t.category].xp,eventsLen:s.events.length,historyLen:s.history.length,status:i.status,rating:i.rating,xp:i.xp,taskCompleted:t.completed,completedDay:t.completedDay,skipStreak:t.category==='mentale'?s.mental.skipStreak:(t.skipStreak||0)};i.status='done';i.rating=r;i.xp=xp;t.completed=true;t.completedDay=s.day;if(t.category==='mentale')s.mental.skipStreak=0;else t.skipStreak=0;addXp(t.category,xp,catLabel(t.category));if(t.category==='palestra')s.stats.gymWorkouts++;if(t.category==='mentale'){s.stats.mentalChallenges++;const k=String(t.difficulty||0);s.stats.mentalByDifficulty[k]=(s.stats.mentalByDifficulty[k]||0)+1}i.statsApplied=true;s.history.push({day:s.day,text:`${t.name} +${xp} XP`});save();renderHome()})};
window.undoCustomComplete=id=>{const t=s.tasks.find(x=>x.id===id),i=s.customDay?.instances?.[id];if(!t||!i||i.status!=='done')return;const u=i.undoComplete;if(u){s.categories[t.category].xp=u.xpBefore;s.events.length=u.eventsLen;s.history.length=u.historyLen;t.completed=u.taskCompleted;if(u.completedDay==null)delete t.completedDay;else t.completedDay=u.completedDay;if(t.category==='mentale')s.mental.skipStreak=u.skipStreak;else t.skipStreak=u.skipStreak}if(i.statsApplied){if(t.category==='palestra')s.stats.gymWorkouts=Math.max(0,s.stats.gymWorkouts-1);if(t.category==='mentale'){s.stats.mentalChallenges=Math.max(0,s.stats.mentalChallenges-1);const k=String(t.difficulty||0);s.stats.mentalByDifficulty[k]=Math.max(0,(s.stats.mentalByDifficulty[k]||0)-1)}}i.status='pending';i.rating=null;i.xp=0;delete i.undoComplete;delete i.statsApplied;save();renderHome()};
function systemTaskName(system,fallback){const t=(s.tasks||[]).find(x=>x.system===system);return t?.name||fallback}
function systemTaskApplies(system){const t=(s.tasks||[]).find(x=>x.system===system);if(!t||!t.active)return false;if(t.availability==='recurring')return (t.weekdays||[]).includes(s.weekday);if(t.availability==='deadline')return !t.completed||t.completedDay===s.day;return true}
function renderHome(){const st=level(s.categories.studio.xp),gy=level(s.categories.palestra.xp),me=level(s.categories.mentale.xp);const mt=s.tasks&&s.tasks.find(t=>t.system==='mental');const showMental=!(mt?.completed&&mt.completedDay<s.day);document.querySelector('#app').innerHTML=`<main class="shell"><header class="top"><h1>OLTREUOMO LV. ${overall()}</h1><div class="cats">Studio Lv.${st.lv} · Palestra Lv.${gy.lv} · Salute mentale Lv.${me.lv}</div><div class="day">OGGI · ${s.weekday} · G.${s.day}</div></header>
${showMental?`<section class="card ${s.mental.status==='done'?'done':''}"><div class="eyebrow">SALUTE MENTALE · LV.${me.lv}</div><div class="title">${s.mental.status==='done'?'✓ '+s.mental.name.toUpperCase():s.mental.name}</div>${s.mental.status==='done'?`<div><span class="xp">+${s.mental.xp} XP</span> · <span class="sub">Valutazione ${s.mental.rating}</span></div><div class="row" style="margin-top:14px"><button class="btn ghost" onclick="undoMentalComplete()">ANNULLA</button></div>`:s.mental.status==='exempt'?'<div class="sub">ESONERATO</div><div class="row" style="margin-top:14px"><button class="btn ghost" onclick="undoMentalExempt()">ANNULLA</button></div>':`<div class="meta">${s.mental.difficulty===0?'Base':'+'+s.mental.difficulty} · ${R().mentalBase} XP base → ${Math.trunc(R().mentalBase*difficultyMult(s.mental.difficulty))} XP · ${s.mental.remaining} ${s.mental.remaining===1?'giorno rimanente':'giorni rimanenti'}</div><div class="row" style="margin-top:14px"><button class="btn green" onclick="mentalComplete()">COMPLETA</button><button class="btn ghost" onclick="exemptMental()">ESONERO</button></div>`}</section>`:''}
${systemTaskApplies('study')?`<section class="card"><div class="eyebrow">STUDIO · LV.${st.lv}</div><div class="title">${systemTaskName('study','Studiare')}</div>${s.study.exempt?'<div class="sub">ESONERATO</div><div class="row" style="margin-top:14px"><button class="btn ghost" onclick="undoStudyExempt()">ANNULLA</button></div>':`<div id="timer" class="timer">${fmt(currentSeconds())}</div><div class="row"><button class="btn ${s.study.running?'red':'green'}" onclick="toggleTimer()">${s.study.running?'TERMINA':'AVVIA'}</button><button class="btn ghost" onclick="exemptStudy()">ESONERO</button></div>`}</section>`:''}
${systemTaskApplies('gym')?`<section class="card ${s.gym.status==='done'?'done':''}"><div class="eyebrow">PALESTRA · LV.${gy.lv}</div><div class="title">${s.gym.status==='done'?`✓ ${systemTaskName('gym','Allenamento').toUpperCase()} — COMPLETATA`:systemTaskName('gym','Allenamento')}</div>${s.gym.status==='done'?`<div><span class="xp">+${s.gym.xp} XP</span> · <span class="sub">Valutazione ${s.gym.rating}</span></div><div class="row" style="margin-top:14px"><button class="btn ghost" onclick="undoGymComplete()">ANNULLA</button></div>`:s.gym.status==='exempt'?'<div class="sub">ESONERATO</div><div class="row" style="margin-top:14px"><button class="btn ghost" onclick="undoGymExempt()">ANNULLA</button></div>':`<div class="meta">${R().gymBase} XP base</div><div class="row" style="margin-top:14px"><button class="btn green" onclick="gymComplete()">COMPLETA</button><button class="btn ghost" onclick="exemptGym()">ESONERO</button></div>`}</section>`:''}${customCards()}
<button class="newday" onclick="openNewDay()">NUOVO GIORNO</button></main>${nav('home')}<dialog id="modal"></dialog>`;save()}
function progressCard(name,key,extra){const l=level(s.categories[key].xp),pct=Math.min(100,l.x/l.next*100);return `<section class="progress-card"><div class="progress-head"><div class="eyebrow">${name.toUpperCase()}</div><strong>LV.${l.lv}</strong></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div><div class="progress-xp">${Math.trunc(l.x)} / ${l.next} XP</div>${extra}</section>`}
window.renderProgress=()=>{const avg=s.stats.studyDays?Math.floor(s.stats.studySeconds/s.stats.studyDays):0;const diff=Object.keys(s.stats.mentalByDifficulty).sort((a,b)=>Number(a)-Number(b)).map(k=>`<span>+${k}: <b>${s.stats.mentalByDifficulty[k]}</b></span>`).join(' · ')||'<span>Nessuna ancora</span>';const hist=s.events.length?s.events.slice().reverse().map(e=>`<div class="history-row"><span>G.${e.day}</span><span>${e.type==='trophy'?`🏆 ${e.name} · +${e.xp} XP`:`${e.category} → LV.${e.to} ${e.type==='up'?'↑':'↓'}`}</span></div>`).join(''):'<div class="empty">Nessun evento registrato da questa versione.</div>';document.querySelector('#app').innerHTML=`<main class="shell"><header class="top"><h1>PROGRESSI</h1><div class="cats">OLTREUOMO LV.${overall()}</div><div class="day">GIORNO ${s.day}</div></header>${progressCard('Studio','studio',`<div class="stats"><div><span>Tempo totale</span><b>${fmtLong(s.stats.studySeconds)}</b></div><div><span>Tempo medio per giornata</span><b>${fmtLong(avg)}</b></div><div><span>Task completate</span><b>${s.stats.studyTasks}</b></div></div>`)}${progressCard('Palestra','palestra',`<div class="stats"><div><span>Allenamenti completati</span><b>${s.stats.gymWorkouts}</b></div></div>`)}${progressCard('Salute mentale','mentale',`<div class="stats"><div><span>Sfide completate</span><b>${s.stats.mentalChallenges}</b></div><div class="difficulty-breakdown">${diff}</div></div>`)}<section class="history"><div class="eyebrow">STORICO</div>${hist}</section></main>${nav('progress')}<dialog id="modal"></dialog>`;save()}

function trophyReward(t){return Math.trunc(R().trophyBase*difficultyMult(t.difficulty))}
window.renderTrophies=()=>{const obtained=s.trophies.filter(t=>t.obtained).length,total=s.trophies.length;const groups=[['studio','STUDIO'],['palestra','PALESTRA'],['mentale','SALUTE MENTALE']].map(([key,label])=>{const cards=s.trophies.filter(t=>t.category===key).map(t=>`<div class="trophy-card ${t.obtained?'obtained':''}"><div class="trophy-icon">${t.obtained?'◆':'◇'}</div><div class="trophy-main"><div class="trophy-name">${t.name}</div><div class="trophy-meta">${t.difficulty===0?'Base':'+'+t.difficulty} · ${t.obtained?t.xpAssigned:trophyReward(t)} XP${t.obtained?` · G.${t.obtainedDay}`:''}</div></div>${t.obtained?'<div class="trophy-state">OTTENUTO</div>':`<button class="btn green trophy-btn" onclick="obtainTrophy('${t.id}')">OTTIENI</button>`}</div>`).join('');return `<section class="trophy-group"><div class="eyebrow">${label}</div>${cards}</section>`}).join('');document.querySelector('#app').innerHTML=`<main class="shell"><header class="top"><h1>TROFEI</h1><div class="cats">${obtained}/${total} ottenuti</div><div class="day">GIORNO ${s.day}</div></header>${groups}</main>${nav('trophies')}<dialog id="modal"></dialog>`;save()}
function showTrophyFx(t,xp){trophyFxBusy=true;const el=document.createElement('div');el.className='trophy-fx';el.innerHTML=`<div class="trophy-fx-card"><div class="trophy-fx-symbol">◆</div><div class="trophy-fx-kicker">TROFEO OTTENUTO</div><div class="trophy-fx-name">${t.name}</div><div class="trophy-fx-reward">+${xp} XP · ${t.categoryLabel.toUpperCase()}</div></div>`;document.body.appendChild(el);requestAnimationFrame(()=>el.classList.add('show'));setTimeout(()=>el.classList.add('leave'),1650);setTimeout(()=>{el.remove();trophyFxBusy=false;playNextLevelFx()},2100)}
window.obtainTrophy=(id)=>{const t=s.trophies.find(x=>x.id===id);if(!t||t.obtained)return;const xp=trophyReward(t);t.obtained=true;t.obtainedDay=s.day;t.xpAssigned=xp;addXp(t.category,xp,t.categoryLabel);s.events.push({day:s.day,type:'trophy',category:t.categoryLabel,name:t.name,xp});s.history.push({day:s.day,text:`🏆 ${t.name} +${xp} XP`});save();renderTrophies();showTrophyFx(t,xp)}


const catLabel=k=>k==='studio'?'Studio':k==='palestra'?'Palestra':'Salute mentale';
const availLabel=a=>a==='recurring'?'Ricorrente':a==='free'?'Libera':'A scadenza';
const typeLabel=t=>t==='time'?'A tempo':'A completamento';
function taskRewardLabel(t){if(t.category==='studio')return `${R().studyXpPerMin} XP/min`;if(t.category==='palestra')return `${R().gymBase} XP base`;const reward=Math.trunc(R().mentalBase*difficultyMult(t.difficulty||0));return `${R().mentalBase} XP base · ${t.difficulty?'+'+t.difficulty:'Base'} → ${reward} XP`}
window.renderManage=()=>{const cards=s.tasks.map(t=>{const completed=t.availability==='deadline'&&t.completed;return `<div class="manage-card ${t.active?'':'suspended'} ${completed?'completed-config':''}"><div class="manage-main"><div class="manage-name">${t.name}${completed?' <span class="completed-badge">COMPLETATA</span>':''}</div><div class="manage-meta">${catLabel(t.category)} · ${typeLabel(t.type)} · ${availLabel(t.availability)}</div><div class="manage-meta">${taskRewardLabel(t)}${t.availability==='recurring'?` · ${t.weekdays.length===7?'Tutti i giorni':t.weekdays.map(x=>x.slice(0,3)).join(' ')}`:t.availability==='deadline'?` · ${t.duration||3} Giorni Oltreuomo · ${t.difficulty?'+'+t.difficulty:'Base'}${completed?` · completata G.${t.completedDay||s.day}`:''}`:''}</div></div><div class="manage-actions"><button class="mini" onclick="editTask('${t.id}')">${completed?'MODIFICA FUTURO':'MODIFICA'}</button>${completed?'':`<button class="mini" onclick="toggleTaskActive('${t.id}')">${t.active?'SOSPENDI':'RIATTIVA'}</button>`}<button class="mini danger" onclick="deleteTask('${t.id}')">ELIMINA</button></div></div>`}).join('');document.querySelector('#app').innerHTML=`<main class="shell"><header class="top"><h1>GESTIONE</h1><div class="cats">Configura Progetto Oltreuomo</div></header><div class="manage-tabs"><button class="manage-tab active">TASK</button><button class="manage-tab" onclick="renderManageTrophies()">TROFEI</button><button class="manage-tab" onclick="renderManageRules()">REGOLE</button></div><button class="newday" onclick="newTask()">+ NUOVO TASK</button><section class="manage-list">${cards||'<div class="empty">Nessun Task configurato.</div>'}</section></main>${nav('manage')}<dialog id="modal"></dialog>`;save()}

window.renderManageTrophies=()=>{const cards=s.trophies.map(t=>`<div class="manage-card ${t.obtained?'completed-config':''}"><div class="manage-main"><div class="manage-name">${t.name}${t.obtained?' <span class="completed-badge">OTTENUTO</span>':''}</div><div class="manage-meta">${catLabel(t.category)} · ${t.difficulty===0?'Base':'+'+t.difficulty} · ${t.obtained?t.xpAssigned:trophyReward(t)} XP</div>${t.obtained?`<div class="manage-meta">Ottenuto G.${t.obtainedDay} · ricompensa storica immutabile</div>`:''}</div>${t.obtained?'':`<div class="manage-actions"><button class="mini" onclick="editTrophy('${t.id}')">MODIFICA</button><button class="mini danger" onclick="deleteTrophy('${t.id}')">ELIMINA</button></div>`}</div>`).join('');document.querySelector('#app').innerHTML=`<main class="shell"><header class="top"><h1>GESTIONE</h1><div class="cats">Configura Progetto Oltreuomo</div></header><div class="manage-tabs"><button class="manage-tab" onclick="renderManage()">TASK</button><button class="manage-tab active">TROFEI</button><button class="manage-tab" onclick="renderManageRules()">REGOLE</button></div><button class="newday" onclick="newTrophy()">+ NUOVO TROFEO</button><section class="manage-list">${cards||'<div class="empty">Nessun Trofeo configurato.</div>'}</section><section class="rule-note">Un Trofeo già ottenuto è storico: nome, difficoltà e XP assegnati non vengono più modificati.</section></main>${nav('manage')}<dialog id="modal"></dialog>`;save()}
window.newTrophy=()=>openTrophyEditor(null)
window.editTrophy=id=>{const t=s.trophies.find(x=>x.id===id);if(!t||t.obtained)return;openTrophyEditor(t)}
function openTrophyEditor(existing){const isNew=!existing,t=existing?{...existing}:{id:'trophy-'+Date.now(),name:'',category:'studio',categoryLabel:'Studio',difficulty:0,obtained:false,obtainedDay:null,xpAssigned:0};const d=document.querySelector('#modal');d.innerHTML=`<button class="close" onclick="modal.close()">×</button><h2>${isNew?'Nuovo Trofeo':'Modifica Trofeo'}</h2><label class="field-label">NOME</label><input id="trophyName" class="field" value="${t.name.replace(/"/g,'&quot;')}" placeholder="Nome del Trofeo"><label class="field-label">CATEGORIA</label><select id="trophyCat" onchange="trophyFormChanged()"><option value="studio" ${t.category==='studio'?'selected':''}>Studio</option><option value="palestra" ${t.category==='palestra'?'selected':''}>Palestra</option><option value="mentale" ${t.category==='mentale'?'selected':''}>Salute mentale</option></select><label class="field-label">DIFFICOLTÀ</label><select id="trophyDifficulty" onchange="trophyFormChanged()">${[0,1,2,3,4,5,6,7,8].map(x=>`<option value="${x}" ${t.difficulty===x?'selected':''}>${x===0?'Base':'+'+x}</option>`).join('')}</select><div class="rule-note" id="trophyRewardNote"></div><button class="btn green full" onclick="saveTrophyEditor('${t.id}',${isNew})">SALVA TROFEO</button>`;window._editingTrophy=t;d.showModal();trophyFormChanged()}
window.trophyFormChanged=()=>{const diff=Number(document.querySelector('#trophyDifficulty')?.value||0),xp=Math.trunc(250*(1+.25*diff));document.querySelector('#trophyRewardNote').textContent=`RICOMPENSA AUTOMATICA · 250 XP base · ${diff===0?'Base':'+'+diff} → ${xp} XP`}
window.saveTrophyEditor=(id,isNew)=>{const t=window._editingTrophy,name=document.querySelector('#trophyName').value.trim();if(!name)return alert('Inserisci un nome.');t.name=name;t.category=document.querySelector('#trophyCat').value;t.categoryLabel=catLabel(t.category);t.difficulty=Number(document.querySelector('#trophyDifficulty').value||0);if(isNew)s.trophies.push(t);else{const old=s.trophies.find(x=>x.id===id);if(!old||old.obtained)return;Object.assign(old,t)}save();document.querySelector('#modal').close();renderManageTrophies()}
window.deleteTrophy=id=>{const t=s.trophies.find(x=>x.id===id);if(!t||t.obtained)return;const d=document.querySelector('#modal');d.innerHTML=`<h2>Elimina Trofeo?</h2><div class="sub">${t.name}</div><p class="confirm-copy">Il Trofeo non ottenuto verrà rimosso. Nessun XP o evento storico verrà modificato.</p><div class="row"><button class="btn ghost" onclick="modal.close()">ANNULLA</button><button class="btn red" onclick="confirmDeleteTrophy('${id}')">ELIMINA</button></div>`;d.showModal()}
window.confirmDeleteTrophy=id=>{const t=s.trophies.find(x=>x.id===id);if(!t||t.obtained)return;s.trophies=s.trophies.filter(x=>x.id!==id);save();document.querySelector('#modal').close();renderManageTrophies()}

window.newTask=()=>openTaskEditor(null);
window.editTask=id=>openTaskEditor(s.tasks.find(t=>t.id===id));
function openTaskEditor(task){const isNew=!task;const t=task?JSON.parse(JSON.stringify(task)):{id:'task-'+Date.now(),name:'',category:'studio',type:'time',availability:'recurring',weekdays:['Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato','Domenica'],duration:3,difficulty:0,active:true,system:null};const d=document.querySelector('#modal');d.innerHTML=`<button class="close" onclick="modal.close()">×</button><h2>${isNew?'Nuovo Task':'Modifica Task'}</h2><label class="field-label">NOME</label><input id="taskName" class="field" value="${t.name.replace(/"/g,'&quot;')}" placeholder="Nome del Task"><label class="field-label">CATEGORIA</label><select id="taskCat" onchange="taskFormChanged()"><option value="studio" ${t.category==='studio'?'selected':''}>Studio</option><option value="palestra" ${t.category==='palestra'?'selected':''}>Palestra</option><option value="mentale" ${t.category==='mentale'?'selected':''}>Salute mentale</option></select><label class="field-label">TIPO</label><select id="taskType"><option value="time" ${t.type==='time'?'selected':''}>A tempo</option><option value="completion" ${t.type==='completion'?'selected':''}>A completamento</option></select><label class="field-label">DISPONIBILITÀ</label><select id="taskAvail" onchange="taskFormChanged()"><option value="recurring" ${t.availability==='recurring'?'selected':''}>Ricorrente</option><option value="free" ${t.availability==='free'?'selected':''}>Libera</option><option value="deadline" ${t.availability==='deadline'?'selected':''}>A scadenza</option></select><div id="conditional"></div><div class="rule-note" id="rewardNote"></div><button class="btn green full" onclick="saveTaskEditor('${t.id}',${isNew})">SALVA TASK</button>`;window._editingTask=t;d.showModal();taskFormChanged()}
window.taskFormChanged=()=>{const t=window._editingTask,cat=document.querySelector('#taskCat').value,av=document.querySelector('#taskAvail').value,box=document.querySelector('#conditional');if(av==='recurring'){const days=['Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato','Domenica'];box.innerHTML=`<label class="field-label">GIORNI</label><div class="weekday-picker">${days.map((x,i)=>`<label><input type="checkbox" value="${x}" ${(t.weekdays||[]).includes(x)?'checked':''}><span>${['L','M','M','G','V','S','D'][i]}</span></label>`).join('')}</div>`}else if(av==='deadline'){box.innerHTML=`<label class="field-label">DURATA IN GIORNI OLTREUOMO</label><input id="taskDuration" class="field" type="number" min="1" value="${t.duration||3}">${cat==='mentale'?`<label class="field-label">DIFFICOLTÀ</label><select id="taskDifficulty">${[0,1,2,3,4,5].map(x=>`<option value="${x}" ${(t.difficulty||0)===x?'selected':''}>${x===0?'Base':'+'+x}</option>`).join('')}</select>`:''}`}else box.innerHTML='';const reward=cat==='studio'?`${R().studyXpPerMin} XP/min × valutazione`:cat==='palestra'?`${R().gymBase} XP base × valutazione`:`${R().mentalBase} XP base × difficoltà × valutazione`;document.querySelector('#rewardNote').textContent='RICOMPENSA AUTOMATICA · '+reward}
window.saveTaskEditor=(id,isNew)=>{const old=s.tasks.find(x=>x.id===id),t=window._editingTask;t.name=document.querySelector('#taskName').value.trim();if(!t.name)return alert('Inserisci un nome.');t.category=document.querySelector('#taskCat').value;t.type=document.querySelector('#taskType').value;t.availability=document.querySelector('#taskAvail').value;if(t.availability==='recurring'){t.weekdays=[...document.querySelectorAll('.weekday-picker input:checked')].map(x=>x.value);if(!t.weekdays.length)return alert('Seleziona almeno un giorno.')}if(t.availability==='deadline'){t.duration=Math.max(1,Number(document.querySelector('#taskDuration').value)||1);t.difficulty=t.category==='mentale'?Number(document.querySelector('#taskDifficulty')?.value||0):0}if(isNew){if(t.availability==='deadline')t.deadlineRemaining=t.duration;s.tasks.push(t)}else{Object.assign(old,t);if(t.availability==='deadline'&&t.deadlineRemaining==null)t.deadlineRemaining=t.duration}syncSystemTask(t);reconcileOpenDay();save();document.querySelector('#modal').close();renderManage()}
function syncSystemTask(t){if(t.system==='study'){/* the current open day stays mutable */}if(t.system==='gym'){}if(t.system==='mental'&&!t.completed){s.mental.name=t.name;s.mental.difficulty=t.difficulty||0;if(s.mental.status==='active')s.mental.remaining=t.duration||s.mental.remaining}}
window.toggleTaskActive=id=>{const t=s.tasks.find(x=>x.id===id);if(!t)return;t.active=!t.active;if(t.system==='study'&&!t.active&&s.study.running){s.study.seconds=currentSeconds();s.study.running=false;s.study.startedAt=null}reconcileOpenDay();save();renderManage()}
window.deleteTask=id=>{const t=s.tasks.find(x=>x.id===id);if(!t)return;const d=document.querySelector('#modal');d.innerHTML=`<h2>Elimina Task?</h2><div class="sub">${t.name}</div><p class="confirm-copy">Il Task sparirà dal futuro. XP, statistiche ed eventi dei Giorni Oltreuomo già chiusi resteranno invariati.</p><div class="row"><button class="btn ghost" onclick="modal.close()">ANNULLA</button><button class="btn red" onclick="confirmDeleteTask('${id}')">ELIMINA</button></div>`;d.showModal()}
window.confirmDeleteTask=id=>{s.tasks=s.tasks.filter(x=>x.id!==id);reconcileOpenDay();save();document.querySelector('#modal').close();renderManage()}

window.renderManageRules=()=>{const r=R();document.querySelector('#app').innerHTML=`<main class="shell"><header class="top"><h1>GESTIONE</h1><div class="cats">Configura Progetto Oltreuomo</div></header><div class="manage-tabs"><button class="manage-tab" onclick="renderManage()">TASK</button><button class="manage-tab" onclick="renderManageTrophies()">TROFEI</button><button class="manage-tab active">REGOLE</button></div><section class="rules-card"><div class="eyebrow">RICOMPENSE</div>${ruleField('ruleStudy','Studio · XP/min',r.studyXpPerMin,.1)}${ruleField('ruleGym','Palestra · XP base',r.gymBase,1)}${ruleField('ruleMental','Salute mentale · XP base',r.mentalBase,1)}${ruleField('ruleTrophy','Trofei · XP base',r.trophyBase,1)}${ruleField('ruleDiff','Incremento difficoltà',r.difficultyStep*100,1,'%')}</section><section class="rules-card"><div class="eyebrow">VALUTAZIONE</div>${ruleField('ruleR1','1 · Male',r.rating1,.05,'×')}${ruleField('ruleR2','2 · Normale',r.rating2,.05,'×')}${ruleField('ruleR3','3 · Molto bene',r.rating3,.05,'×')}</section><section class="rules-card"><div class="eyebrow">SKIP</div>${ruleField('ruleSkipStart','Penalità dal numero di Skip',r.skipStart,1)}${ruleField('ruleSkipBase','Penalità iniziale',r.skipBase,1,' XP')}${ruleField('ruleSkipGrowth','Crescita per Skip',r.skipGrowth,.05,'×')}</section><section class="rules-card"><div class="eyebrow">CURVA LIVELLI</div><div class="sub rules-help">XP richiesti per ogni livello nelle fasce 1–5, 6–10, …, 36+.</div><div class="level-grid">${r.levelBands.map((v,i)=>`<label><span>${['1–5','6–10','11–15','16–20','21–25','26–30','31–35','36+'][i]}</span><input id="band${i}" class="field" type="number" min="1" step="1" value="${v}"></label>`).join('')}</div></section><section class="rule-note">Le ricompense già chiuse restano storiche. Le regole si applicano al Giorno Oltreuomo aperto; modificare la curva livelli ricalcola subito i livelli dal totale XP.</section><button class="newday" onclick="saveRules()">SALVA REGOLE</button><section class="rules-card backup-card"><div class="eyebrow">BACKUP DATI</div><div class="sub rules-help">Esporta una copia completa dei dati locali o ripristina un backup precedente.</div><button class="btn green full" onclick="exportBackup()">ESPORTA BACKUP</button><button class="btn full backup-import" onclick="document.querySelector('#backupFile').click()">IMPORTA BACKUP</button><input id="backupFile" type="file" accept="application/json,.json" hidden onchange="importBackup(this)"></section></main>${nav('manage')}<dialog id="modal"></dialog>`;save()}
function ruleField(id,label,value,step,suffix=''){return `<label class="rule-row"><span>${label}</span><span class="rule-input-wrap"><input id="${id}" class="field rule-input" type="number" min="0" step="${step}" value="${value}"><em>${suffix}</em></span></label>`}
window.saveRules=()=>{const old={...R()};const nr={...R(),studyXpPerMin:num('ruleStudy',.1),gymBase:num('ruleGym',1),mentalBase:num('ruleMental',1),trophyBase:num('ruleTrophy',1),difficultyStep:num('ruleDiff',0)/100,rating1:num('ruleR1',0),rating2:num('ruleR2',0),rating3:num('ruleR3',0),skipStart:Math.max(1,Math.trunc(num('ruleSkipStart',1))),skipBase:num('ruleSkipBase',0),skipGrowth:num('ruleSkipGrowth',0),levelBands:[0,1,2,3,4,5,6,7].map(i=>Math.max(1,Math.trunc(num('band'+i,1))))};
// Il giorno aperto è mutabile: se Palestra è già completata, adegua solo il suo evento corrente.
if(s.gym.status==='done'&&s.gym.rating){const newXp=Math.trunc(nr.gymBase*(s.gym.rating===1?nr.rating1:s.gym.rating===2?nr.rating2:nr.rating3));const delta=newXp-s.gym.xp;if(delta){s.rules=nr;addXp('palestra',delta,'Palestra');s.gym.xp=newXp}else s.rules=nr}else s.rules=nr;
// Stessa regola per una sfida Salute mentale completata nel giorno ancora aperto.
const mt=s.tasks?.find(t=>t.system==='mental');if(s.mental.status==='done'&&mt?.completedDay===s.day&&s.mental.rating){const newXp=Math.trunc(nr.mentalBase*(1+nr.difficultyStep*s.mental.difficulty)*(s.mental.rating===1?nr.rating1:s.mental.rating===2?nr.rating2:nr.rating3));const delta=newXp-s.mental.xp;if(delta){addXp('mentale',delta,'Salute mentale');s.mental.xp=newXp}}
save();renderManageRules();toast('Regole salvate')}
function num(id,min){const v=Number(document.querySelector('#'+id)?.value);return Number.isFinite(v)?Math.max(min,v):min}

window.exportBackup=()=>{const payload={app:'Progetto Oltreuomo',formatVersion:1,exportedAt:new Date().toISOString(),storageKey:K,state:s};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`progetto-oltreuomo-backup-G${s.day}-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)};
window.importBackup=async input=>{const file=input.files&&input.files[0];if(!file)return;try{const raw=await file.text();const data=JSON.parse(raw);const candidate=data&&data.app==='Progetto Oltreuomo'&&data.state?data.state:data;if(!candidate||typeof candidate!=='object'||!candidate.categories||!candidate.day||!Array.isArray(candidate.tasks)||!Array.isArray(candidate.trophies))throw new Error('invalid');if(!confirm('IMPORTA BACKUP?\n\nI dati attuali verranno sostituiti dal contenuto del backup.')){input.value='';return}localStorage.setItem(K,JSON.stringify(candidate));location.reload()}catch(e){input.value='';alert('Backup non valido o non leggibile. I dati attuali non sono stati modificati.')}};
function toast(text){const d=document.querySelector('#modal');d.innerHTML=`<h2>${text}</h2><div class="sub">Le nuove regole sono attive.</div><button class="btn green full" onclick="modal.close()">OK</button>`;d.showModal()}

window.toggleTimer=()=>{if(s.study.running){s.study.seconds=currentSeconds();s.study.running=false;s.study.startedAt=null}else{s.study.running=true;s.study.startedAt=Date.now()}renderHome()};
window.exemptStudy=()=>{s.study.undoExempt={seconds:s.study.seconds,running:s.study.running,startedAt:s.study.startedAt};if(s.study.running){s.study.seconds=currentSeconds();s.study.running=false;s.study.startedAt=null}s.study.exempt=true;renderHome()};
window.undoStudyExempt=()=>{const u=s.study.undoExempt;s.study.exempt=false;if(u){s.study.seconds=u.running?currentSeconds():u.seconds;s.study.running=false;s.study.startedAt=null;delete s.study.undoExempt}renderHome()};
window.exemptGym=()=>{s.gym.status='exempt';renderHome()};window.undoGymExempt=()=>{if(s.gym.status==='exempt')s.gym.status='pending';renderHome()};
window.exemptMental=()=>{s.mental.status='exempt';renderHome()};window.undoMentalExempt=()=>{if(s.mental.status==='exempt')s.mental.status='active';renderHome()};
function rateDialog(title,base,cb,allowSkip=false){const d=document.querySelector('#modal');d.innerHTML=`<button class="close" onclick="modal.close()">×</button><h2>${title}</h2><div class="sub">Scegli la valutazione</div><div class="choice"><button class="btn ghost" onclick="chooseRate(ratingMult(1),1)">1<br>Male</button><button class="btn ghost" onclick="chooseRate(ratingMult(2),2)">2<br>Normale</button><button class="btn ghost" onclick="chooseRate(ratingMult(3),3)">3<br>Molto bene</button></div>${allowSkip?'<button class="btn red full" onclick="chooseSkip()">SKIP</button>':''}`;window.chooseRate=(m,r)=>{d.close();cb(Math.trunc(base*m),r)};window.chooseSkip=()=>{d.close();cb(null,null,true)};d.showModal()}
window.mentalComplete=()=>{const base=R().mentalBase*difficultyMult(s.mental.difficulty);rateDialog('Sfida completata',base,(xp,r)=>{s.mental.undoComplete={xpBefore:s.categories.mentale.xp,skipStreak:s.mental.skipStreak,eventsLen:s.events.length,historyLen:s.history.length,mentalChallenges:s.stats.mentalChallenges,diffCount:s.stats.mentalByDifficulty[String(s.mental.difficulty)]||0};s.mental.status='done';s.mental.rating=r;s.mental.xp=xp;const mt=s.tasks&&s.tasks.find(t=>t.system==='mental');if(mt){mt.completed=true;mt.completedDay=s.day;}s.mental.skipStreak=0;addXp('mentale',xp,'Salute mentale');s.stats.mentalChallenges++;const k=String(s.mental.difficulty);s.stats.mentalByDifficulty[k]=(s.stats.mentalByDifficulty[k]||0)+1;s.history.push({day:s.day,text:`Salute mentale +${xp} XP`});renderHome()})};
window.undoMentalComplete=()=>{if(s.mental.status!=='done')return;const u=s.mental.undoComplete;if(u){s.categories.mentale.xp=u.xpBefore;s.mental.skipStreak=u.skipStreak;s.events.length=u.eventsLen;s.history.length=u.historyLen;s.stats.mentalChallenges=u.mentalChallenges;const k=String(s.mental.difficulty);s.stats.mentalByDifficulty[k]=u.diffCount}else{s.categories.mentale.xp=Math.max(0,s.categories.mentale.xp-(s.mental.xp||0));s.stats.mentalChallenges=Math.max(0,s.stats.mentalChallenges-1);const k=String(s.mental.difficulty);s.stats.mentalByDifficulty[k]=Math.max(0,(s.stats.mentalByDifficulty[k]||0)-1)}const mt=s.tasks&&s.tasks.find(t=>t.system==='mental');if(mt&&mt.completedDay===s.day){mt.completed=false;delete mt.completedDay}s.mental.status='active';s.mental.rating=null;s.mental.xp=0;delete s.mental.undoComplete;renderHome()};
window.gymComplete=()=>rateDialog(`${systemTaskName('gym','Allenamento')} completato`,R().gymBase,(xp,r)=>{s.gym.undoComplete={xpBefore:s.categories.palestra.xp,skipStreak:s.gym.skipStreak,eventsLen:s.events.length,historyLen:s.history.length,gymWorkouts:s.stats.gymWorkouts};s.gym.status='done';s.gym.rating=r;s.gym.xp=xp;s.gym.skipStreak=0;addXp('palestra',xp,'Palestra');s.stats.gymWorkouts++;s.history.push({day:s.day,text:`Palestra +${xp} XP`});renderHome()});
window.undoGymComplete=()=>{if(s.gym.status!=='done')return;const u=s.gym.undoComplete;if(u){s.categories.palestra.xp=u.xpBefore;s.gym.skipStreak=u.skipStreak;s.events.length=u.eventsLen;s.history.length=u.historyLen;s.stats.gymWorkouts=u.gymWorkouts}else{s.categories.palestra.xp=Math.max(0,s.categories.palestra.xp-(s.gym.xp||0));s.stats.gymWorkouts=Math.max(0,s.stats.gymWorkouts-1)}s.gym.status='pending';s.gym.rating=null;s.gym.xp=0;delete s.gym.undoComplete;renderHome()};
function prepareCustomTimeRatings(done){
 reconcileOpenDay();
 const tasks=customVisibleTasks().filter(t=>t.type==='time');
 tasks.forEach(t=>{const i=s.customDay.instances[t.id];if(i?.running){i.seconds=customSeconds(t.id);i.running=false;i.startedAt=null}});
 let n=0;
 const next=()=>{if(n>=tasks.length){save();done();return}const t=tasks[n++],i=s.customDay.instances[t.id];if(!i||i.status==='exempt'||i.status==='done'){next();return}const secs=i.seconds||0;if(secs<=0){i.dayResult={kind:t.availability==='free'?'none':'skip'};next();return}const mins=secs/60,shown=mins<1?`${secs} sec`:`${Math.floor(mins)} min`,base=mins*(t.category==='studio'?R().studyXpPerMin:0);rateDialog(`${t.name} · ${shown}`,base,(xp,r,skip)=>{i.dayResult=skip?{kind:'skip'}:{kind:'done',xp,rating:r};next()},t.availability!=='free')};
 next()
}
window.openNewDay=()=>{const studyApplies=systemTaskApplies('study');if(s.study.running){s.study.seconds=currentSeconds();s.study.running=false;s.study.startedAt=null;save()}const proceed=()=>prepareCustomTimeRatings(()=>{if(!studyApplies){finishDay(null,null,false);return}const secs=s.study.seconds;if(secs>0&&!s.study.exempt){const mins=secs/60;const shown=mins<1?`${secs} sec`:`${Math.floor(mins)} min`;rateDialog(`${systemTaskName('study','Studiare')} · ${shown}`,mins*R().studyXpPerMin,(xp,r,skip)=>finishDay(skip?null:xp,r,skip),true)}else finishDay(null,null,!s.study.exempt)});proceed()};
function finishDay(studyXp,rating,studySkip){
 const studyApplies=systemTaskApplies('study'),gymApplies=systemTaskApplies('gym');
 const studyIsSkip=studyApplies&&studyXp==null&&!s.study.exempt,nextStudyStreak=studyIsSkip?(s.study.skipStreak||0)+1:(s.study.skipStreak||0),studyPenalty=studyIsSkip?skipPenalty(nextStudyStreak):0;
 const gymPending=gymApplies&&s.gym.status==='pending',nextGymStreak=gymPending?s.gym.skipStreak+1:s.gym.skipStreak,gymPenalty=gymPending&&skipPenalty(nextGymStreak);
 const d=document.querySelector('#modal'),days=['Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato','Domenica'],next=days[(days.indexOf(s.weekday)+1)%7];
 const rows=[];
 if(studyApplies)rows.push(`<div class="summary">${systemTaskName('study','Studiare')}: ${studyXp!=null?`<span class="xp">+${studyXp} XP</span>`:s.study.exempt?'Esonero':`<span class="negative">Skip ${nextStudyStreak}${studyPenalty?` · −${studyPenalty} XP`:''}</span>`}</div>`);
 if(gymApplies)rows.push(`<div class="summary">${systemTaskName('gym','Allenamento')}: ${s.gym.status==='done'?`<span class="xp">+${s.gym.xp} XP</span>`:s.gym.status==='exempt'?'Esonero':`<span class="negative">Skip ${nextGymStreak}${gymPenalty?` · −${gymPenalty} XP`:''}</span>`}</div>`);
 const mt=s.tasks?.find(t=>t.system==='mental');
 if(s.mental.status==='done'&&mt?.completedDay===s.day)rows.push(`<div class="summary">Salute mentale: <span class="xp">+${s.mental.xp} XP</span></div>`);
 else if(s.mental.status==='exempt'&&mt&&!mt.completed)rows.push(`<div class="summary">Salute mentale: Esonero</div>`);
 else if(s.mental.status==='active'&&mt&&!mt.completed){rows.push(`<div class="summary">Salute mentale: ${s.mental.remaining>1?`Attiva · ${s.mental.remaining-1} ${s.mental.remaining-1===1?'giorno rimanente':'giorni rimanenti'}`:`<span class="negative">Skip ${s.mental.skipStreak+1}${skipPenalty(s.mental.skipStreak+1)?` · −${skipPenalty(s.mental.skipStreak+1)} XP`:''}</span>`}</div>`)}
 const customTimes=customVisibleTasks().filter(t=>t.type==='time');
 customTimes.forEach(t=>{const i=s.customDay?.instances?.[t.id];if(!i)return;if(i.status==='exempt'){rows.push(`<div class="summary">${t.name}: Esonero</div>`);return}const res=i.dayResult;if(res?.kind==='done'){rows.push(`<div class="summary">${t.name}: <span class="xp">+${res.xp} XP</span></div>`);return}if(res?.kind==='skip'&&t.availability!=='free'){const ns=(t.skipStreak||0)+1,pen=skipPenalty(ns);rows.push(`<div class="summary">${t.name}: <span class="negative">Skip ${ns}${pen?` · −${pen} XP`:''}</span></div>`)}});
 const customCompletions=customVisibleTasks().filter(t=>t.type!=='time'&&t.availability!=='deadline');
 customCompletions.forEach(t=>{const i=s.customDay?.instances?.[t.id];if(!i)return;if(i.status==='done'){rows.push(`<div class="summary">${t.name}: <span class="xp">+${i.xp} XP</span></div>`);return}if(i.status==='exempt'){rows.push(`<div class="summary">${t.name}: Esonero</div>`);return}if(t.availability==='recurring'){const ns=(t.skipStreak||0)+1,pen=skipPenalty(ns);rows.push(`<div class="summary">${t.name}: <span class="negative">Skip ${ns}${pen?` · −${pen} XP`:''}</span></div>`)}});
 const customDeadlines=(s.tasks||[]).filter(t=>!t.system&&t.active&&t.availability==='deadline'&&(!t.completed||t.completedDay===s.day));
 customDeadlines.forEach(t=>{ensureDeadlineState(t);const i=s.customDay?.instances?.[t.id];if(t.completed&&t.completedDay===s.day&&i?.status==='done'){rows.push(`<div class="summary">${t.name}: <span class="xp">+${i.xp} XP</span></div>`);return}if(i?.status==='exempt')rows.push(`<div class="summary">${t.name}: Esonero</div>`);else if(t.deadlineRemaining>1)rows.push(`<div class="summary">${t.name}: Attiva · ${t.deadlineRemaining-1} ${t.deadlineRemaining-1===1?'giorno rimanente':'giorni rimanenti'}</div>`);else{const streak=t.category==='mentale'?(s.mental.skipStreak||0)+1:(t.skipStreak||0)+1,pen=skipPenalty(streak);rows.push(`<div class="summary">${t.name}: <span class="negative">Skip ${streak}${pen?` · −${pen} XP`:''}</span></div>`)}});
 d.innerHTML=`<h2>Chiudi G.${s.day}</h2>${rows.join('')}<label class="sub">PROSSIMO GIORNO</label><select id="wd">${days.map(x=>`<option ${x===next?'selected':''}>${x}</option>`).join('')}</select><div class="row"><button class="btn ghost" onclick="modal.close()">ANNULLA</button><button class="btn green" onclick="confirmDay()">CONFERMA NUOVO GIORNO</button></div>`;
 window.confirmDay=()=>{
  if(studyXp!=null){s.study.skipStreak=0;addXp('studio',studyXp,'Studio');s.stats.studySeconds+=s.study.seconds;s.stats.studyDays++;s.stats.studyTasks++;s.history.push({day:s.day,text:`Studio +${studyXp} XP`})}else if(studyIsSkip){s.study.skipStreak=nextStudyStreak;if(studyPenalty){addXp('studio',-studyPenalty,'Studio');s.history.push({day:s.day,text:`Studio −${studyPenalty} XP`})}}
  if(gymPending){s.gym.skipStreak=nextGymStreak;if(gymPenalty){addXp('palestra',-gymPenalty,'Palestra');s.history.push({day:s.day,text:`Palestra −${gymPenalty} XP`})}}
  if(s.mental.status==='active'&&mt&&!mt.completed){if(s.mental.remaining>1)s.mental.remaining--;else{const ms=s.mental.skipStreak+1;s.mental.skipStreak=ms;const mp=skipPenalty(ms);if(mp){addXp('mentale',-mp,'Salute mentale');s.history.push({day:s.day,text:`Salute mentale −${mp} XP`})}mt.completed=true;mt.expired=true;mt.completedDay=s.day}}
  customTimes.forEach(t=>{const i=s.customDay?.instances?.[t.id];if(!i||i.status==='exempt')return;const res=i.dayResult;if(res?.kind==='done'){t.skipStreak=0;addXp(t.category,res.xp,catLabel(t.category));if(t.category==='studio'){s.stats.studySeconds+=(i.seconds||0);s.stats.studyTasks++;}s.history.push({day:s.day,text:`${t.name} +${res.xp} XP`})}else if(res?.kind==='skip'&&t.availability!=='free'){const ns=(t.skipStreak||0)+1;t.skipStreak=ns;const pen=skipPenalty(ns);if(pen){addXp(t.category,-pen,catLabel(t.category));s.history.push({day:s.day,text:`${t.name} −${pen} XP`})}}});
  customCompletions.forEach(t=>{const i=s.customDay?.instances?.[t.id];if(!i)return;if(i.status==='done'){if(t.availability==='recurring'){t.completed=false;delete t.completedDay}return}if(i.status==='exempt'||t.availability==='free')return;const ns=(t.skipStreak||0)+1;t.skipStreak=ns;const pen=skipPenalty(ns);if(pen){addXp(t.category,-pen,catLabel(t.category));s.history.push({day:s.day,text:`${t.name} −${pen} XP`})}});
  customDeadlines.forEach(t=>{const i=s.customDay?.instances?.[t.id];if(t.completed&&t.completedDay===s.day&&i?.status==='done')return;if(i?.status==='exempt')return;if(t.deadlineRemaining>1)t.deadlineRemaining--;else{const ns=t.category==='mentale'?(s.mental.skipStreak||0)+1:(t.skipStreak||0)+1;if(t.category==='mentale')s.mental.skipStreak=ns;else t.skipStreak=ns;const pen=skipPenalty(ns);if(pen){addXp(t.category,-pen,catLabel(t.category));s.history.push({day:s.day,text:`${t.name} −${pen} XP`})}t.completed=true;t.expired=true;t.completedDay=s.day}});
  s.day++;s.weekday=document.querySelector('#wd').value;s.study={seconds:0,running:false,startedAt:null,exempt:false,skipStreak:s.study.skipStreak||0};s.gym={status:'pending',rating:null,xp:0,skipStreak:s.gym.skipStreak};s.customDay={day:s.day,instances:{}};d.close();save();renderHome()
 };
 d.showModal()
}
window.renderHome=renderHome;renderHome();setInterval(()=>{const el=document.querySelector('#timer');if(el&&s.study.running)el.textContent=fmt(currentSeconds());if(s.customDay)Object.entries(s.customDay.instances||{}).forEach(([id,i])=>{const e=document.querySelector('#ct-'+id);if(e&&i.running)e.textContent=fmt(customSeconds(id))})},1000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
